"""Emitters: css/scss/tailwind/json shape, sorting, determinism."""

import json

from chromakey import __version__
from chromakey import emit

FLAT = {
    "color-ink": "#252524",
    "color-paper": "#DFDFDF",
    "space-base": "4px",
}


def test_css_header_and_sorted():
    out = emit.css(FLAT)
    lines = out.splitlines()
    assert lines[0] == "/* generated by chromakey %s — do not edit */" % __version__
    assert lines[1] == ":root {"
    assert lines[-1] == "}"
    names = [line.split("--")[1].split(":")[0] for line in lines[2:-1]]
    assert names == sorted(names) == ["color-ink", "color-paper", "space-base"]


def test_css_lowercases_colors():
    out = emit.css({"color-accent": "#ABCDEF"})
    assert "--color-accent: #abcdef;" in out


def test_css_without_root():
    out = emit.css({"a-x": "#111111"}, root=False)
    assert ":root" not in out
    assert "--a-x: #111111;" in out


def test_scss_shape():
    out = emit.scss(FLAT)
    lines = out.splitlines()
    assert lines[0].startswith("// generated by chromakey ")
    assert "$color-ink: #252524;" in out
    assert "$color-paper: #dfdfdf;" in out
    assert "$space-base: 4px;" in out


def test_tailwind_groups_by_first_segment():
    out = emit.tailwind(FLAT)
    assert "module.exports = {" in out
    assert "colors: {" in out  # brief: module.exports = { colors: {...} }
    assert '"color": {' in out
    assert '"space": {' in out
    assert out.index('"color": {') < out.index('"space": {')
    assert '"ink": "#252524"' in out
    assert '"base": "4px"' in out
    assert out.rstrip().endswith("};")


def test_json_sorted_two_space():
    out = emit.json(FLAT)
    assert out.startswith('{\n  "color-ink": "#252524",\n')
    assert json.loads(out) == FLAT
    # keys appear in sorted order, 2-space indent
    positions = [out.index('"%s"' % k) for k in sorted(FLAT)]
    assert positions == sorted(positions)


def test_determinism_byte_stable():
    reversed_flat = dict(reversed(list(FLAT.items())))
    for fn in (emit.css, emit.scss, emit.tailwind, emit.json):
        assert fn(FLAT) == fn(reversed_flat), fn.__name__
    assert emit.css(FLAT) == emit.css(FLAT)
    assert emit.json(FLAT) == emit.json(FLAT)
