"""CLI: exit codes, file output, JSON summaries, determinism."""

import json

import pytest

from chromakey import cli


def run(*argv):
    try:
        return cli.main(list(argv))
    except SystemExit as exc:
        code = exc.code
        return code if isinstance(code, int) else 2


def test_build_all_writes_four_files(tmp_path, sample_tokens):
    out = tmp_path / "out"
    code = run("build", str(sample_tokens), "--all", "--out", str(out))
    assert code == 0
    names = sorted(p.name for p in out.iterdir())
    assert names == ["tokens.css", "tokens.json", "tokens.scss", "tokens.tailwind.js"]
    css = (out / "tokens.css").read_text(encoding="utf-8")
    assert css.splitlines()[0].startswith("/* generated by chromakey")
    assert ":root {" in css
    assert (out / "tokens.tailwind.js").read_text(encoding="utf-8").startswith(
        "// generated by chromakey"
    )


def test_build_two_runs_byte_identical(tmp_path, sample_tokens):
    a = tmp_path / "a"
    b = tmp_path / "b"
    assert run("build", str(sample_tokens), "--all", "--out", str(a)) == 0
    assert run("build", str(sample_tokens), "--all", "--out", str(b)) == 0
    for name in ("tokens.css", "tokens.json", "tokens.scss", "tokens.tailwind.js"):
        assert (a / name).read_bytes() == (b / name).read_bytes()


def test_build_single_format(tmp_path, sample_legacy):
    out = tmp_path / "out"
    assert run("build", str(sample_legacy), "--format", "css", "--out", str(out)) == 0
    assert sorted(p.name for p in out.iterdir()) == ["legacy.css"]


def test_contrast_json_shape(capsys, sample_tokens):
    code = run("contrast", str(sample_tokens), "--all", "--json")
    assert code == 0
    data = json.loads(capsys.readouterr().out)
    assert data["total"] == len(data["pairs"]) > 0
    assert set(data["pairs"][0]) == {"name", "a", "b", "ratio", "aa", "aa_large", "aaa"}


def test_contrast_strict_exit_codes(sample_tokens):
    assert run("contrast", str(sample_tokens), "--pairs", "#000000,#FFFFFF", "--strict") == 0
    assert run("contrast", str(sample_tokens), "--pairs", "#FFFFFF,#FFFFFF", "--strict") == 1
    assert run("contrast", str(sample_tokens), "--pairs", "#FFFFFF,#FFFFFF") == 0


def test_contrast_table_output(capsys, sample_tokens):
    assert run("contrast", str(sample_tokens), "--pairs", "#000000,#FFFFFF") == 0
    out = capsys.readouterr().out
    assert "21.00:1" in out
    assert "AA ✓" in out
    assert "AAA ✓" in out


def test_contrast_all_vs_pairs_flags(sample_tokens):
    assert run("contrast", str(sample_tokens), "--all") == 0
    assert run("contrast", str(sample_tokens)) == 2
    assert run("contrast", str(sample_tokens), "--pairs", "#111111") == 2


def test_missing_file_exit_2(tmp_path):
    assert run("build", str(tmp_path / "nope.json")) == 2
    assert run("validate", str(tmp_path / "nope.json")) == 2
    assert run("preview", str(tmp_path / "nope.json")) == 2


def test_validate_bad_file_exit_1(tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text(
        json.dumps({"color-bad": "#GGG", "bad_name": "#252524"}), encoding="utf-8"
    )
    assert run("validate", str(bad)) == 1
    good = tmp_path / "good.json"
    good.write_text(json.dumps({"color-ink": {"$value": "#252524"}}), encoding="utf-8")
    assert run("validate", str(good)) == 0


def test_validate_json_problems(capsys, tmp_path):
    bad = tmp_path / "bad.json"
    bad.write_text(json.dumps({"color-bad": "#GGG"}), encoding="utf-8")
    assert run("validate", str(bad), "--json") == 1
    data = json.loads(capsys.readouterr().out)
    assert data["ok"] is False
    assert any(p["path"] == "color-bad" for p in data["problems"])


def test_palette_json(capsys):
    assert run("palette", "#22AC80", "--steps", "5", "--json") == 0
    data = json.loads(capsys.readouterr().out)
    assert data["base"] == "#22ac80"
    assert data["n"] == 5
    assert len(data["steps"]) == 5


def test_palette_bad_hex_exit_1():
    assert run("palette", "#GGGGGG") == 1


def test_preview_writes_html(tmp_path, sample_tokens):
    target = tmp_path / "preview.html"
    assert run("preview", str(sample_tokens), "--out", str(target)) == 0
    html = target.read_text(encoding="utf-8")
    assert "Atelier tokens" in html
    assert "http" not in html
    assert "<script" not in html


def test_preview_contains_all_token_names(tmp_path, sample_tokens):
    from chromakey import tokens as tokens_mod

    text = sample_tokens.read_text(encoding="utf-8")
    flat = tokens_mod.resolve(tokens_mod.load(json.loads(text)))
    target = tmp_path / "p.html"
    assert run("preview", str(sample_tokens), "--out", str(target)) == 0
    html = target.read_text(encoding="utf-8")
    for name in flat:
        assert name in html, "missing token name %s in preview.html" % name


def test_version():
    with pytest.raises(SystemExit) as exc:
        cli.main(["--version"])
    assert exc.value.code == 0


def test_no_command_exit_2():
    assert run() == 2
