"""Deterministic emitters: css, scss, tailwind, json.

All outputs are byte-stable: tokens sorted by name, canonical
lowercase hex colors, no timestamps. The header banner carries the
version (it is pinned, so output is stable across runs).
"""

import json as _json

from chromakey import __version__
from chromakey.hexx import valid as _hex_valid

__all__ = ["css", "scss", "tailwind", "json", "CSS_HEADER", "SCSS_HEADER"]

CSS_HEADER = "/* generated by chromakey %s — do not edit */" % __version__
SCSS_HEADER = "// generated by chromakey %s — do not edit" % __version__


def _norm(value):
    """Canonicalize a token value for text emitters (colors lowercase)."""
    if isinstance(value, str):
        stripped = value.strip()
        if stripped.startswith("#") and _hex_valid(stripped):
            return stripped.lower()
        return stripped
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def css(flat, root=True):
    """``:root { --name: value; }`` lines sorted by name, with header."""
    lines = [CSS_HEADER]
    if root:
        lines.append(":root {")
        lines.extend("  --%s: %s;" % (name, _norm(flat[name])) for name in sorted(flat))
        lines.append("}")
    else:
        lines.extend("--%s: %s;" % (name, _norm(flat[name])) for name in sorted(flat))
    return "\n".join(lines) + "\n"


def scss(flat):
    """``$name: value;`` lines sorted by name, with header."""
    lines = [SCSS_HEADER]
    lines.extend("$%s: %s;" % (name, _norm(flat[name])) for name in sorted(flat))
    return "\n".join(lines) + "\n"


def _group(flat):
    groups = {}
    for name in sorted(flat):
        if "-" in name:
            head, tail = name.split("-", 1)
        else:
            head, tail = name, name
        groups.setdefault(head, {})[tail] = _norm(flat[name])
    return groups


def _js_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return _json.dumps(value, ensure_ascii=False)


def _js_object(obj, indent):
    pad = "  " * indent
    lines = []
    for key in sorted(obj):
        value = obj[key]
        if isinstance(value, dict):
            lines.append('%s"%s": %s' % (pad, key, _js_object(value, indent + 1)))
        else:
            lines.append('%s"%s": %s' % (pad, key, _js_value(value)))
    return "{\n" + ",\n".join(lines) + "\n" + "  " * (indent - 1) + "}"


def tailwind(flat):
    """Plain-JS text: ``module.exports = { colors: {...} }`` grouped by
    the first name segment. No Node required — it is just text."""
    groups = _group(flat)
    lines = [SCSS_HEADER, "module.exports = {", "  colors: {"]
    heads = sorted(groups)
    for i, head in enumerate(heads):
        suffix = "," if i < len(heads) - 1 else ""
        lines.append('    "%s": %s%s' % (head, _js_object(groups[head], 3), suffix))
    lines.append("  }")
    lines.append("};")
    return "\n".join(lines) + "\n"


def json(flat):
    """Sorted JSON, 2-space indent, ``ensure_ascii=False``."""
    return (
        _json.dumps(dict(sorted(flat.items())), indent=2, sort_keys=True, ensure_ascii=False)
        + "\n"
    )
